# Generated by Django 4.2.7 on 2023-12-05 14:15

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='upload',
            field=models.FileField(blank=True, upload_to=chat.models.message_file_path),
        ),
    ]
